---
- name: Create file on all app servers
  hosts: all
  become: yes

  tasks:
    - name: Create /tmp/appdata.txt with correct permissions and ownership
      ansible.builtin.file:
        path: /tmp/appdata.txt
        state: touch
        mode: '0755'
        owner: "{{ owner_user }}"
        group: "{{ owner_user }}"
